# Generated by Django 5.0.3 on 2026-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('MORTUARY', 'Mortuary'), ('TRANSPORT', 'Transport'), ('CATERING', 'Catering'), ('VENUE', 'Venue'), ('EQUIPMENT', 'Equipment Rental'), ('PRINTING', 'Printing'), ('MUSIC', 'Music/Entertainment'), ('OTHER', 'Other')], max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('QUOTED', 'Quote Received'), ('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('COMPLETED', 'Service Completed'), ('CANCELLED', 'Cancelled')], default='QUOTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_providers',
                'ordering': ['-created_at'],
            },
        ),
    ]
