# Generated by Django 5.0.3 on 2026-03-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_budget_allocation_committee_committee_type_and_more'),
        ('events', '0003_budget_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('OTHER', 'Other Action')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text="Model/table that was modified (e.g., 'BudgetItem')", max_length=100)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object that was modified')),
                ('object_repr', models.CharField(help_text='String representation of the object', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Dictionary of field changes: {'field': {'old': value, 'new': value}}")),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Memorial Service', 'Budget Meeting'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the schedule item')),
                ('schedule_type', models.CharField(choices=[('SUB_EVENT', 'Sub Event'), ('MEETING', 'Meeting'), ('ANNOUNCEMENT', 'Announcement'), ('PROGRAM_ITEM', 'Program Item'), ('DEADLINE', 'Deadline'), ('OTHER', 'Other')], default='PROGRAM_ITEM', max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='When the event/activity starts')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When the event/activity ends (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text="Physical or virtual location (e.g., 'Zoom link')", max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this appears in public program/announcements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPROVAL_PENDING', 'Approval Pending'), ('DEPOSIT_CONFIRMED', 'Deposit Confirmed'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('TASK_ASSIGNED', 'Task Assigned'), ('BUDGET_ADJUSTED', 'Budget Adjusted'), ('MEETING_REMINDER', 'Meeting Reminder'), ('SCHEDULE_PUBLISHED', 'Schedule Published'), ('PAYMENT_APPROVED', 'Payment Approved'), ('OTHER', 'Other')], help_text='Category/type of notification', max_length=30)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('BOTH', 'SMS and Email')], default='SMS', help_text='Delivery channel (SMS, Email, or Both)', max_length=10)),
                ('subject', models.CharField(help_text='Email subject or SMS preview', max_length=255)),
                ('message', models.TextField(help_text='Full notification message body')),
                ('phone_number', models.CharField(blank=True, help_text='Recipient phone number for SMS', max_length=20)),
                ('email_address', models.EmailField(blank=True, help_text='Recipient email address', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was successfully sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('related_object_model', models.CharField(blank=True, help_text="Model name of related object (e.g., 'BudgetItem')", max_length=100)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='budgetadjustmentrequest',
            new_name='events_budg_budget__37ce8f_idx',
            old_name='events_budg_budget__8f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='budgetadjustmentrequest',
            new_name='events_budg_request_526c24_idx',
            old_name='events_budg_request_9a4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='events_budg_event_i_68ef4d_idx',
            old_name='events_budg_event_i_cb8f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='events_budg_committ_3264b0_idx',
            old_name='events_budg_committ_7a2e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='budgetitem',
            new_name='events_budg_created_3222b2_idx',
            old_name='events_budg_created_4e1b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='clustercontribution',
            new_name='events_clus_cluster_f0c118_idx',
            old_name='events_clus_cluster_idx2',
        ),
        migrations.RenameIndex(
            model_name='clustercontribution',
            new_name='events_clus_is_pled_2a19b8_idx',
            old_name='events_clus_is_pled_idx',
        ),
        migrations.RenameIndex(
            model_name='clustercontribution',
            new_name='events_clus_payment_00796e_idx',
            old_name='events_clus_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='clusterdeposit',
            new_name='events_clus_cluster_fda182_idx',
            old_name='events_clus_cluster_idx3',
        ),
        migrations.RenameIndex(
            model_name='clusterdeposit',
            new_name='events_clus_confirm_7c96b8_idx',
            old_name='events_clus_confirm_idx',
        ),
        migrations.RenameIndex(
            model_name='clusterdeposit',
            new_name='events_clus_deposit_818315_idx',
            old_name='events_clus_deposit_idx',
        ),
        migrations.RenameIndex(
            model_name='clustergroup',
            new_name='events_clus_event_i_0f9235_idx',
            old_name='events_clus_event_i_idx',
        ),
        migrations.RenameIndex(
            model_name='clustergroup',
            new_name='events_clus_cluster_310995_idx',
            old_name='events_clus_cluster_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_d_432a97_idx',
            old_name='events_even_event_d_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_5709b6_idx',
            old_name='events_even_status_idx',
        ),
        migrations.RenameIndex(
            model_name='eventmember',
            new_name='events_even_event_i_228906_idx',
            old_name='events_even_event_i_idx',
        ),
        migrations.RenameIndex(
            model_name='eventmember',
            new_name='events_even_user_id_889bb9_idx',
            old_name='events_even_user_id_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event',
            field=models.ForeignKey(help_text='Event this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='events.event'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='committee',
            field=models.ForeignKey(blank=True, help_text='Subcommittee responsible for this schedule item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_items', to='committees.committee'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event',
            field=models.ForeignKey(help_text='Main event this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(help_text='Event this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event', '-timestamp'], name='events_audi_event_i_8bba93_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='events_audi_user_id_a3f8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='events_audi_model_n_29ac7c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='events_audi_timesta_7d18ce_idx'),
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['event', 'start_datetime'], name='events_even_event_i_068d90_idx'),
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['status', 'is_public'], name='events_even_status_7cda45_idx'),
        ),
        migrations.AddIndex(
            model_name='eventschedule',
            index=models.Index(fields=['committee'], name='events_even_committ_516e12_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event', 'status'], name='events_noti_event_i_d94e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='events_noti_recipie_ed76f5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='events_noti_status_1e2aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='events_noti_notific_eb43ae_idx'),
        ),
    ]
