# Generated by Django 5.0.3 on 2026-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auditlog_eventschedule_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='role',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('EVENT_OWNER', 'Event Owner'), ('TEAM_LEAD', 'Team Lead'), ('CLUSTER_LEAD', 'Cluster Lead'), ('MEMBER', 'Committee Member')], default='MEMBER', max_length=20),
        ),
    ]
