# Generated by Django 5.0.3 on 2026-03-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auditlog_eventschedule_notification_and_more'),
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Cluster group if collection is from fundraising cluster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='events.clustergroup'),
        ),
        migrations.AddField(
            model_name='collection',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Main event this collection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='events.event'),
        ),
        migrations.AddField(
            model_name='collection',
            name='source_type',
            field=models.CharField(choices=[('CLUSTER', 'Cluster Group'), ('GENERAL', 'General/Direct')], default='GENERAL', help_text='Whether from cluster fundraising or general donation', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_chair',
            field=models.ForeignKey(blank=True, help_text='Chairman approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved_as_chair', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_finance',
            field=models.ForeignKey(blank=True, help_text='Finance committee member approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved_as_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by_treasurer',
            field=models.ForeignKey(blank=True, help_text='Treasurer approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved_as_treasurer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_item',
            field=models.ForeignKey(blank=True, help_text='Budget item this expense is charged against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='events.budgetitem'),
        ),
        migrations.AddField(
            model_name='expense',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Main event this expense belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.event'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was made', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED_CHAIR', 'Approved by Chair'), ('APPROVED_TREASURER', 'Approved by Treasurer'), ('APPROVED_FINANCE', 'Approved by Finance Member'), ('FULLY_APPROVED', 'Fully Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
