# Generated by Django 5.0.3 on 2026-03-29 17:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auditlog_eventschedule_notification_and_more'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Main event this task belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Task completion percentage (0-100)', max_digits=5),
        ),
    ]
