# Generated by Django 5.0.3 on 2026-03-29 17:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_initial'),
        ('events', '0003_budget_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='budget_allocation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget allocated to this committee', max_digits=12),
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(choices=[('MAIN', 'Main Committee'), ('BUDGET_FINANCE', 'Budget & Finance Committee'), ('FUNDS_MOBILIZATION', 'Funds Mobilization Committee'), ('LOGISTICS', 'Logistics'), ('CATERING', 'Catering'), ('VENUE', 'Venue'), ('TRANSPORT', 'Transport'), ('MEDIA', 'Media & Communications'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='OTHER', help_text='Type/function of this committee', max_length=30),
        ),
        migrations.AddField(
            model_name='committee',
            name='deadline',
            field=models.DateField(blank=True, help_text='Deadline for committee deliverables', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Main event this committee belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcommittees', to='events.event'),
        ),
        migrations.AddField(
            model_name='committee',
            name='expected_activities',
            field=models.TextField(blank=True, help_text='Expected activities and responsibilities'),
        ),
        migrations.AddField(
            model_name='committee',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Whether this is the main/umbrella committee'),
        ),
        migrations.AddField(
            model_name='committee',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lead/chairperson of this committee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='event_type',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='committee',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
    ]
