# Generated by Django 5.0.3 on 2026-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_budget_allocation_committee_committee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='role',
            field=models.CharField(choices=[('TEAM_LEAD', 'Team Lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
